#Syntax Highlighting
"attribute" = "#b7410e"
"type" = "#ff2400"
"constructor" = "#ffc66d"
"constant" = "#ffa500"
"constant.numeric" = "#ff2400"
"string" = "#6a8759"
"string.regex" = { fg = "#ffa500", underline = { color = "#ffa500", style = "line" } }
"string.special.path" = { fg = "#ffa500", modifiers = ["italic"] }
"string.special.url" = { fg = "#ffa500", modifiers = ["italic"] }
"string.special.symbol" = "#b7410e"
"comment" = { fg = "#ffa500", modifiers = ["italic"] }
"variable" = "#ff6600"
"variable.parameter" = { fg = "#ff6600", underline = { color = "#ff6600", style = "line" }, modifiers = [
  "italic",
] }
"variable.other.member" = { fg = "#ff2400" }
"label" = { fg = "#ffa500", underline = { color = "#ffa500", style = "line" } }
"punctuation" = "#b7410e"
"punctuation.delimiter" = "#b7410e"
"punctuation.special" = "#b7410e"
"keyword" = "#cc8242"
"operator" = "#b7410e"
"function" = "#ffc66d"
"tag" = "#ff6600"
"namespace" = "#ff6600"

#html and markup
"markup.heading" = "#6a8759"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "#ffa500", modifiers = ["italic"] }
"markup.link.text" = "#6a8759"
"markup.raw" = "#6a8759"

#git indicators
"diff.plus" = "#2EA043"
"diff.minus" = "#f85149"
"diff.delta" = "#0078D4"

#Interface Colors
"ui.background" = "#1f1f1f"
"ui.background.separator" = { fg = "#cccccc" }
"ui.cursor" = { bg = "#ebdbb2" }
"ui.cursor.select" = { bg = "#ebdbb2" }
"ui.cursor.match" = { bg = "#ebdbb2" }
"ui.cursor.primary" = { bg = "#ebdbb2" }
"ui.gutter" = "#1f1f1f"
"ui.gutter.selected" = "#1f1f1f"
"ui.linenr" = "#ffa500"
"ui.linenr.selected" = "#ff6600"
"ui.statusline" = { fg = "#cccccc", bg = "#1f1f1f" }
"ui.statusline.inactive" = { fg = "#cccccc", bg = "#1f1f1f" }
"ui.statusline.separator" = "|"
"ui.popup" = { fg = "#cccccc", bg = "#1f1f1f" }
"ui.popup.info" = { fg = "#cccccc", bg = "#1f1f1f" }
"ui.window" = { fg = "#cccccc", bg = "#1f1f1f" }
"ui.help" = { fg = "#cccccc", bg = "#1f1f1f" }
"ui.text" = { fg = "#cccccc" }
"ui.text.info" = { fg = "#cccccc" }
"ui.text.focus" = { fg = "#784f26" }
"ui.text.inactive" = "#cccccc"
"ui.virtual.ruler" = { bg = "#d45c00" }
"ui.menu" = { fg = "#cccccc", bg = "#1f1f1f" }
"ui.menu.selected" = { fg = "#cccccc", bg = "#784f26" }
"ui.menu.scroll" = { fg = "#cccccc", bg = "#1f1f1f" }
"ui.selection" = { bg = "#784f26" }
"ui.virtual.wrap" = "#ffc66d"
"ui.virtual.inlay-hint" = { fg = "#cccccc", modifiers = ["italic", "bold"] }
"warning" = { fg = "#ff942f", bg = "#1f1f1f" }
"error" = { fg = "#e45454", bg = "#1f1f1f" }
"info" = { fg = "#00b7e4", bg = "#1f1f1f" }
"hint" = { fg = "#2faf64", bg = "#1f1f1f" }
"diagnostic" = { underline = { style = "line" } }
"diagnostic.error" = { underline = { style = "curl", color = "#e45454" } }
"diagnostic.warning" = { underline = { style = "curl", color = "#ff942f" } }
"diagnostic.info" = { underline = { style = "curl", color = "#00b7e4" } }
"diagnostic.hint" = { underline = { style = "curl", color = "#2faf64" } }
