cursor #cecdc3
cursor_text_color #cecdc3

foreground            #cecdc3
background            #100f0f
selection_foreground  #100f0f
selection_background  #da702c
url_color             #da702c

color0   #100F0F
color1   #fa281e
color2   #4bda2b
color3   #ffd71f
color4   #d55b0f
color5   #642700
color6   #DA702C
color7   #e4d7ce
color8   #8d837c
color9   #ff6d66
color10  #8aff70
color11  #ffe570
color12  #ef8c4d
color13  #ffa870
color14  #ffc7a3
color15  #fff8f4
