#!/usr/bin/env bash
# ===============================================
# Greeter Monitor Layout Sync (greetd/dms-greeter)
# ===============================================
# dms-greeter runs its own tiny Hyprland session for the login screen, which
# knows nothing about your real monitor layout (rotation, position, refresh
# rate) unless it's told. Left alone, the greeter falls back to a default
# layout that can land monitors in the wrong orientation/position compared
# to your logged-in session.
#
# This script reads DMS's own generated Hyprland output config
# (~/.config/hypr/dms/outputs.conf) -- the source of truth for your current
# monitor layout -- and regenerates /etc/greetd/dms-hypr-monitors.lua from
# it, so the greeter always mirrors whatever layout DMS currently has set.
# It also makes sure /etc/greetd/config.toml actually passes that file to
# dms-greeter via `-C`.
#
# Safe to re-run any time your monitor layout changes (new monitor,
# re-arranged positions, rotation). No-ops if the greeter is already in
# sync.
#
# Must be run in a real interactive terminal: sudo needs to prompt for your
# password, which won't work piped through a non-interactive shell.
set -euo pipefail
IFS=$'\n\t'

DOTFILES_DIR="${DOTFILES_DIR:-$HOME/dotfiles}"
source "${DOTFILES_DIR}/install/lib.sh"

LOG_FILE="${LOG_DIR}/regen-greeter-monitors.log"
init_log "$LOG_FILE"

ensure_gum

banner "Greeter Monitor Layout Sync"

SRC="${XDG_CONFIG_HOME}/hypr/dms/outputs.conf"
DEST="/etc/greetd/dms-hypr-monitors.lua"
CONFIG_TOML="/etc/greetd/config.toml"

if [[ ! -f "$SRC" ]]; then
	fail_message "Source layout not found: $SRC (is DMS/Hyprland set up on this machine?)"
fi

# --- 1. Convert Hyprland `monitor = ...` lines into hl.monitor({...}) calls ---
# outputs.conf lines look like:
#   monitor = DP-1, 2560x1440@143.998, 0x0, 1, transform, 1, vrr, 0
# i.e. output, mode, position, scale, then arbitrary keyword/value pairs.
lua_line_from_monitor() {
	local raw="$1"
	raw="${raw#*=}"          # drop "monitor ="
	raw="${raw%%#*}"         # drop trailing comment, if any

	local -a fields=()
	local field
	while IFS= read -r field; do
		field="${field#"${field%%[![:space:]]*}"}"
		field="${field%"${field##*[![:space:]]}"}"
		fields+=("$field")
	done < <(tr ',' '\n' <<<"$raw")

	[[ ${#fields[@]} -ge 4 ]] || return 1

	local out="{ output = \"${fields[0]}\", mode = \"${fields[1]}\", position = \"${fields[2]}\", scale = \"${fields[3]}\""

	local i=4
	while (( i + 1 < ${#fields[@]} )); do
		local key="${fields[i]}" val="${fields[i+1]}"
		out+=", ${key} = ${val}"
		i=$((i + 2))
	done
	out+=" }"

	echo "hl.monitor(${out})"
}

info_message "Reading monitor layout from ${SRC}..."
LUA_BODY=""
while IFS= read -r line; do
	[[ "$line" =~ ^[[:space:]]*monitor[[:space:]]*= ]] || continue
	lua_line="$(lua_line_from_monitor "$line")" || {
		warn_message "Skipping unparsable line: $line"
		continue
	}
	LUA_BODY+="${lua_line}"$'\n'
done <"$SRC"

if [[ -z "$LUA_BODY" ]]; then
	fail_message "No monitor lines found in ${SRC}. Refusing to write an empty layout."
fi

TMP_LUA="$(mktemp /tmp/dms-hypr-monitors.XXXXXX.lua)"
trap 'rm -f "$TMP_LUA"' EXIT

cat >"$TMP_LUA" <<EOF
-- Monitor layout for the DMS/greetd login screen (Hyprland).
-- Mirrors ${SRC/#$HOME/\~} so the greeter matches the logged-in session.
-- dms-greeter appends its own quickshell/session-start hook to this file automatically
-- (via -C), so this file should contain ONLY compositor settings like monitors/input.
--
-- Auto-generated by regen-greeter-monitors.sh -- re-run it after changing your
-- monitor layout instead of editing this file by hand.

${LUA_BODY}
EOF

# --- 2. Compare against what's live and install if it changed ---
if [[ -f "$DEST" ]] && diff -q "$TMP_LUA" "$DEST" &>/dev/null; then
	okay_message "Greeter monitor layout already up to date. Nothing to do."
else
	if [[ -f "$DEST" ]]; then
		info_message "Layout changed -- diff:"
		diff -u "$DEST" "$TMP_LUA" || true
	else
		info_message "No existing ${DEST} -- creating it."
	fi
	info_message "Installing updated layout to ${DEST} (will prompt for your sudo password)..."
	sudo install -D -m 0644 "$TMP_LUA" "$DEST" || fail_message "Failed to install ${DEST}."
	okay_message "Greeter monitor layout updated."
fi

# --- 3. Make sure config.toml actually points dms-greeter at it ---
if [[ -f "$CONFIG_TOML" ]] && grep -q -- "-C ${DEST}" "$CONFIG_TOML"; then
	okay_message "${CONFIG_TOML} already wired to ${DEST}."
elif [[ -f "$CONFIG_TOML" ]] && grep -q '^command = .*--command hyprland' "$CONFIG_TOML"; then
	info_message "Wiring ${CONFIG_TOML} to load ${DEST} (will prompt for your sudo password)..."
	sudo cp "$CONFIG_TOML" "${CONFIG_TOML}.bak-$(date +%Y%m%d)"
	sudo sed -i "s|--command hyprland|--command hyprland -C ${DEST}|" "$CONFIG_TOML" \
		|| fail_message "Failed to update ${CONFIG_TOML}."
	okay_message "${CONFIG_TOML} updated (backup saved alongside it)."
else
	warn_message "Could not find an expected 'command = ... --command hyprland' line in ${CONFIG_TOML}. Leaving it untouched -- check it points dms-greeter at ${DEST} via -C."
fi

# --- 4. Clear greetd's failure lockout, if any, so the new config takes on next login ---
if systemctl list-unit-files greetd.service &>/dev/null; then
	sudo systemctl reset-failed greetd &>/dev/null || true
fi

finish "Greeter monitor layout is in sync. Changes take effect on next login screen (VT switch or reboot to preview)."
